[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle all routes through React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
