[build]
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment-specific settings
[context.production.environment]
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_API_URL = "https://cbt-rew7.onrender.com"

[context.deploy-preview.environment]
  REACT_APP_ENVIRONMENT = "preview"
  REACT_APP_API_URL = "https://cbt-rew7.onrender.com" 