[build]
  base = "frontend"
  publish = "build"
  command = "npm ci --audit-level=moderate && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_AUDIT_LEVEL = "moderate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment-specific settings
[context.production.environment]
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_API_URL = "https://cbt-rew7.onrender.com"
  REACT_APP_USE_API = "true"

[context.deploy-preview.environment]
  REACT_APP_ENVIRONMENT = "preview"
  REACT_APP_API_URL = "https://cbt-rew7.onrender.com"
  REACT_APP_USE_API = "true" 