[build]
  base = "frontend"
  publish = "build"
  command = "CI=false npm install && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_AUDIT_LEVEL = "moderate"
  NPM_CONFIG_PRODUCTION = "false"
  CI = "false"

# Ensure we're in the right directory
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment-specific settings
[context.production.environment]
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_API_URL = "https://cbt-rew7.onrender.com"
  REACT_APP_USE_API = "false"

[context.deploy-preview.environment]
  REACT_APP_ENVIRONMENT = "preview"
  REACT_APP_API_URL = "https://cbt-rew7.onrender.com"
  REACT_APP_USE_API = "false"

[context.branch-deploy.environment]
  REACT_APP_ENVIRONMENT = "branch"
  REACT_APP_API_URL = "https://cbt-rew7.onrender.com"
  REACT_APP_USE_API = "false" 