services:
  - type: web
    name: cbt-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --production=false
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DB_TYPE
        value: mongodb 